version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Danil122003
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: . 
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/blog
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Danil122003
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_FLYWAY_ENABLED=true
    ports:
      - "8081:8081"
    # volumes:
    #   - ./application-docker.properties:/app/application.properties # (Опционально) если хотите внешний конфиг

volumes:
  postgres_data: